### PR TITLE
Fixing cli checking file extensions

### PR DESCRIPTION
**Pull request by atkaiser**
Proposed fix for #385 by just removing the `any` and using `or` for the booleans instead.

### CODE REVIEW

**Comment by mrooney** [comment]
Thanks! I wonder why the `any` wouldn't work, I would think that is functionally the same. Just adding @burkematthew since he wrote this to see if this seems like the best fix.

**Comment by burkematthew** [comment]
@mrooney @atkaiser 

I'll take a look at this tomorrow and see if I can figure out what's going on.

**Comment by jaron-l** [comment]
They're not the same because the `or` allows the following tests to not be evaluated if `filename` is none. They code fails as is because when `filename` is none, it doesn't have the endswith attribute.

**Review by jaron-l — APPROVED** [review]

**Comment by mrooney** [comment]
@jaron-l thanks for the review and merge, @atkaiser thanks for the PR!

**Pull request merged**
