### PR TITLE
[FEATURE] - Added bills download to mintapi cli

### PR DESCRIPTION
**Pull request by BillJr99**
Added a constants key for mint bills, a cli option --bills to download bill data from mint, and a call to mint.get_bills if that option is set.

### CODE REVIEW

**Comment by mrooney** [comment]
Nice, great addition, thanks! Was this manually tested/verified?

**Comment by BillJr99** [comment]
You bet, and thanks for maintaining this!  I have not tested it extensively beyond my own mint account, but the cli does return the correct array of bills for my account.

**Comment by BillJr99** [comment]
Looks like the lint check had failed, possibly due to line endings or whitespace.  I didn't have the action enabled on my fork.  I re-formatted with black and re-committed to this pull request if you'd like to re-run the checks on this end.

**Comment by mrooney** [comment]
Thanks! For some reason GH shows the whole cli.py file as being rewritten. Is it possible spacing was changed, or changed to tabs, or similar?

**Comment by BillJr99** [comment]
Looks like black changed all the line endings from unix to windows, but somehow only on that file!  I reverted to fix the line endings, and re-committed.  The linter also broke up a few help message string constants, but I left those in case that's preferrable.

**Comment by BillJr99** [comment]
Sure thing.  I agree - I prefer not to have extraneous edits in a commit.  On my local repository, the black action now fails this commit because it still wants to break up those strings, but I'd assume it would continue to pass here.

**Review by burkematthew — APPROVED** [review]
Even though bills is still a bit out-of-sync with the rest of the endpoints, this by itself is good.  Thanks @BillJr99 for your contribution!

**Comment by mrooney** [comment]
Thanks @BillJr99 ! Perhaps we need to have a contributor guide that specifies the version/arguments for black so it all aligns. Sorry for the troubles!

**Pull request merged**
