### PR TITLE
[FIX] Fix issue with user selection page by updating CSS Selector

### PR DESCRIPTION
**Pull request by CalvinChanCan**
As @snowskeleton mentioned in #549 , there is also a sign in issue with the updated CSS in the user selection page. The issue can be recreated by passing your own webdriver but using your own Chrome User Profile that has been previously logged in. Since mint already has a session saved, it should go through the user selection page flow and then raise an error for not finding "Use a different user ID" button.

This PR should address this issue for anyone else going through the user selection page flow.

A side note, but the general new CSS selector trend seems to be `data-testid=`.

### CODE REVIEW

**Comment by CalvinChanCan** [comment]
@felciano thanks for testing this! When I was using my Chrome User Profile I had thought Chrome had been just autofilling my username. However, I believe that mint now populates the email input field already with the email from the session. But for some reason `email_input.clear()` is not actually clearing the value in the email input and so we get the email inputted twice. So my workaround now uses a loop to send backspace keys the length of the email to remove the email autofilled by mint.

**Comment by burkematthew** [comment]
@CalvinChanCan have you tried waiting for the element to be clickable to make sure that we can actually click to clear?

https://stackoverflow.com/a/49151715

**Comment by CalvinChanCan** [comment]
@burkematthew Thanks! The waiting for the `email_input` to be clickable worked! I added in the WebDriverWait and changed it back to clear the input rather than the workaround with the backspaces.

**Comment by CalvinChanCan** [comment]
@burkematthew So I took a closer look and had thought waiting for the email input and then attempting to cleared it work. But I accidentally removed `email_input.send_keys(email)` so it had been using the email address from the session already.

I tried waiting for the email input, then attempted to add the email to the email but its showing up as "USERNAME USERNAME" again. From the stackoverflow link, I tried adding a click before inputting the email but still getting not able to successfully clear the email.

```
        email_input = WebDriverWait(driver, 20).until(
            expected_conditions.element_to_be_clickable(
                (
                    By.CSS_SELECTOR,
                    '#ius-identifier, [data-testid="IdentifierFirstIdentifierInput"]',
                )
            )
        )
        if not email_input.is_displayed():
            raise ElementNotVisibleException()

        email_input.click()
        email_input.clear()
        email_input.send_keys(email)
```

**Comment by felciano** [comment]
I tried `1d8ce4e` and it is now completing the login sequence as expected (username, password and MFA), but then fails out on a
```
selenium.common.exceptions.WebDriverException: Message: disconnected: received Inspector.detached event
```
which was not happening before. Are you seeing this as well? This is with a default `mintapi` call using soft-tokens:

```
poetry run mintapi --keyring --mfa-method=soft-token --mfa-token "SOFTTOKEN" "USERNAME"
```

**Comment by felciano** [comment]
@CalvinChanCan actually I'm fairly certain that the above `received Inspector.detached event` is #546 and independent of the login issue this patch is trying to address. From my perspective, this patch successfully re-enables automated login and is good to go

**Comment by CalvinChanCan** [comment]
Hmm I'm not quite sure this patch is working as intended. It certainly is getting through the user selection page but its odd that it does when I accidentally left out `email_input.send_keys(email)`. So what I think is happening is that mint is still using the email from the session rather than the email we're passing into the mintapi constructor. 

I have tried a few ways of trying to get the email to successfully clear but haven't found anything that works besides the backspace method. @burkematthew , do you have any thoughts if we should revert back to the backspace method or what we can do to resolve this issue?

**Comment by felciano** [comment]
I believe this patch fixes #545 (referenced here to track it)

**Comment by CalvinChanCan** [comment]
I'll close this PR since this does not seem to be an issue.

**Pull request closed without merging**
