### PR TITLE
Able to set the WebDriver to use in constructor

### PR DESCRIPTION
**Pull request by zsolteszku**
Usecase: Anyone could pass their own custom webdriver to the Mint. This will enable users to run the script on AWS Lambda (where you would need to have a special headless chrome to be able to run) or any container where a customer driver is necessary.

### CODE REVIEW

**Comment by mrooney** [comment]
Looks pretty straightforward, thanks! Can you update the PR and ideally README / docs with the use-case this addresses?

**Review by mrooney — CHANGES_REQUESTED** [review]
Looks pretty straightforward, thanks! Can you update the PR and ideally README / docs with the use-case this addresses?

**Comment by zsolteszku** [comment]
Usecase: Anyone could pass their own custom webdriver to the Mint. This will enable users to run the script on AWS Lambda (where you would need to have a special headless chrome to be able to run) or any container where a customer driver is necessary.

@mrooney Would you like me to include this usecase in the README?

**Comment by burkematthew** [comment]
@zsolteszku yes a README update would be great, thanks!

**Comment by mrooney** [comment]
@zsolteszku Agreed, that would be fantastic, especially if it had an example for how to do this on AWS with the appropriate driver :)

**Comment by zsolteszku** [comment]
@burkematthew and @mrooney updated the README.md, let me know your thoughts.

**Review by burkematthew — APPROVED** [review]

**Review by mrooney — APPROVED** [review]

**Pull request merged**
