### PR TITLE
feat: :sparkles: Expose sign_in as a public method to allow custom WebDrivers

### PR DESCRIPTION
**Pull request by jaron-l**
* show deprecation warning on get_web_driver
* refactor login_and_get_token to cover get_web_driver
* document how to use sign_in with custom WebDriver

refs: #330

This is a proposal to replace #330 which will allow the user to specify custom WebDrivers so we don't have to explicitly expose every requested feature.

### CODE REVIEW

**Comment by mrooney** [comment]
Looks pretty cool to me, I can't really think of any downside. It doesn't seem like it adds any real complexity to the code (you did a bunch of cleanup, actually :), and makes more setups possible. Nice!

**Comment by mrooney** [comment]
(That said, I do think if this replaces #330, we should still improve the README for simpler cases where the user just wants to know how to specify PATH properly in a cron or script)

**Comment by jaron-l** [comment]
> (That said, I do think if this replaces #330, we should still improve the README for simpler cases where the user just wants to know how to specify PATH properly in a cron or script)

I just added a commit that should address this. Let me know what you think.

**Comment by jaron-l** [comment]
@mrooney just in case you didn't see, I addressed your previous comment. Let me know if you have any more feedback.

**Review by mrooney — APPROVED** [review]
Awesome, thanks for this slick improvement, LGTM!

**Pull request merged**
