### PR TITLE
Allows user to explicitly specify path to preferred [Chrome/Chromium] browser

### PR DESCRIPTION
**Pull request by llorracc**
Without further configuration, mintapi launches the system default version of Chrome.  That can be inconvenient if (for example) you are using chrome for other things.  This allows the user to specify a path to an alternative binary executable, which runs independently of whatever browsers the user might already have going. 

Example:

mintapi me@my.domain.org --alternative-browser-path /usr/local/share/chromium-extra-binary

The code right now is formatted to make it easy to see the parallels to the existing code for "chromedriver-download-path" rather than for elegance.  Should be reformatted to look better before merging.

### CODE REVIEW

**Comment by mrooney** [comment]
Thanks for your contribution! Have you tried using the existing use_chromedriver_on_path and/or headless options to solve this?

**Comment by jaron-l** [comment]
@mrooney he's talking about which chrome binary executable to use, i.e. if you have more than one chrome version installed. This is different from which chromedriver to use.

**Comment by llorracc** [comment]
@jaron-l is right.  I was trying to solve the problem that running mintapi with a cron job meant that if the job ran while I was using Chrome the Chrome instance for mintapi would have various annoying interactions with my ongoing Chrome session.  This PR solves that problem by allowing the user to tell mintapi to use, say, a browser that they never use for any other purpose (e.g., Chromium).  Hence no interference.

**Comment by jaron-l** [comment]
Can you add this to the README.md so that it is easy for others to see that this is an option?

**Comment by mrooney** [comment]
+1 for README! Thanks for the contribution. This might also help raspberry pi users :)

**Comment by burkematthew** [comment]
@jaron-l @mrooney I propose that we close this one now that #330 is open with the necessary requested adjustments.

**Pull request closed without merging**
