### PR TITLE
🧹 Validate file extension before data is retrieved

### PR DESCRIPTION
**Pull request by burkematthew**
This PR includes the following:
* Create a method to perform output filename extensions _before_ we retrieve data.
* Create a method to output the data
* Add test cases for validating that the new filename extension validator works.
* Addresses one of the concerns raised in #88

### CODE REVIEW

**Review by mrooney — CHANGES_REQUESTED** [review]
Seems like a helpful approach to the user and I like the abstraction of the output_data function and test coverage :)

One request: unless I'm missing something, could we just use TemporaryFile instead of NamedTemporaryFile? If we don't need a specific location on disk, it seems potentially more portable, since we are returning the object for writing anyway and not grabbing it by location later.

**Comment by burkematthew** [comment]
> Seems like a helpful approach to the user and I like the abstraction of the output_data function and test coverage :)
> 
> One request: unless I'm missing something, could we just use TemporaryFile instead of NamedTemporaryFile? If we don't need a specific location on disk, it seems potentially more portable, since we are returning the object for writing anyway and not grabbing it by location later.

@mrooney we're using NamedTemporaryFile since we're building a config file to then pass along to parse our command line options, including that of the filename. I ran into some issues with TemporaryFile persisting when implementing the config file test awhile back. If you want me to push through and keep trying, I certainly can. Just let me know!

**Comment by mrooney** [comment]
> > Seems like a helpful approach to the user and I like the abstraction of the output_data function and test coverage :)
> > One request: unless I'm missing something, could we just use TemporaryFile instead of NamedTemporaryFile? If we don't need a specific location on disk, it seems potentially more portable, since we are returning the object for writing anyway and not grabbing it by location later.
> 
> @mrooney we're using NamedTemporaryFile since we're building a config file to then pass along to parse our command line options, including that of the filename. I ran into some issues with TemporaryFile persisting when implementing the config file test awhile back. If you want me to push through and keep trying, I certainly can. Just let me know!

No worries, in that case I'm good, I just wanted to make sure there was a good reason :)

**Review by mrooney — APPROVED** [review]
Thanks!

**Pull request merged**
