### PR TITLE
prevent email MFA check from marking messages as read

### PR DESCRIPTION
**Pull request by tsdg112**
The fixes a problem that happens when checking email for the MFA code.  When it reads non-MFA messages, they would be marked as read.  This fixes that problem.

It also adds a check for an additional cause of sign-in failure: when you are temporarily blocked by Mint.

### CODE REVIEW

**Comment by mrooney** [comment]
Thanks! LGTM to me on both accounts but would also love a review from @burkematthew as I'm not nearly as familiar with the email flow.

**Comment by burkematthew** [comment]
@mrooney I'll try and take a look at this this weekend. If it looks good, I'll approve as well and then merge.

**Comment by tsdg112** [comment]
Mint made a minor change to the email subject.  The latest commit allows both the old and new subject.

**Comment by mrooney** [comment]
Thanks for the update with both versions :) @burkematthew if you happen to get a minute, I would love to know if all looks well to you.

**Review by burkematthew — APPROVED** [review]

**Pull request merged**
