### PR TITLE
Ignore `LICENSE.chromedriver` file

### PR DESCRIPTION
**Pull request by snowskeleton**
I just had these start showing up in my project folder.

### CODE REVIEW

**Comment by mrooney** [comment]
Thanks! Since this is one specific file, could we just add a line for it explicitly?

**Comment by snowskeleton** [comment]
how's that look? I also moved it up with the other `chromedrive` ignore

**Comment by mrooney** [comment]
Nice, thanks :D

**Review by mrooney — APPROVED** [review]

**Comment by mrooney** [comment]
I would think `chromedriver*` makes `chromedriver` redundant but I'm not positive. Of course that wasn't introduced in this PR so it's strictly better now :)

**Pull request merged**
