### PR TITLE
Re-throw exception during login

### PR DESCRIPTION
**Pull request by zsolteszku**
By silencing the exception in the `login_and_get_token` the code execution could still continue without an explicit try-except which would could end up additional calls to a `WebDriver` that was already closed (by `quit()`) that leads to confusing error messages (similar to `MaxRetryError("HTTPConnectionPool(host='127.0.0.1', port=55873): Max retries exceeded with url: /session/2dd60780e17e5d8d8e1cdf9496086729/window_handles`)

Could be related to issue: #387

### CODE REVIEW

**Comment by burkematthew** [comment]
@zsolteszku we are redoing a lot of login flow in the PR#392. Can you check out this branch and see if your issue persists? Also, I'd greatly appreciate any testing feedback you could provide so I could get more perspectives of login flow.

**Comment by zsolteszku** [comment]
@burkematthew I tested the new branch and this issue still persist there as well as the exception is not re-thrown.

**Comment by burkematthew** [comment]
@zsolteszku thank you for testing that out! I'll review your change.

**Review by burkematthew — APPROVED** [review]

**Comment by mrooney** [comment]
Amazing, thanks for the fix with test! 👯

**Pull request merged**
