### PR TITLE
[CHORE] - Update the README, CHANGELOG and more tidying of method names

### PR DESCRIPTION
**Pull request by burkematthew**
As discussed on #458 , the names of the methods have changed from v1 and so we need some updates to the README, more explicit callout in the CHANGELOG, and we need to make some more tweaks\tidying to the actual method names to ensure consistency.  Note that `get_bills` is an exception because it does NOT use the same execution structure as the others.

### CODE REVIEW

**Comment by mrooney** [comment]
Thanks! Am I correct in understanding that all the methods which you've renamed in this PR have had their input and/or output changed and they are being renamed to be consistent with the other breaking method changes?

**Comment by burkematthew** [comment]
Yes and no. Some of them don't have any output changes, but I thought it was important to keep consistency in the naming convention across our methods. Improves usability so that one method isn't `get_budgets` and another is `get_account_data`. The remaining ones I changed in this PR was more about that consistency.

**Comment by burkematthew** [comment]
@mrooney any other comments?

**Review by mrooney — APPROVED** [review]
Thanks, looks good! Before we release, I'll do a re-review of the changes and adjust some things in prominence; this looks great for now!

**Pull request merged**
