### PR TITLE
Add additional CSS selectors for signin process

### PR DESCRIPTION
**Pull request by apiology**
The current set does not match what I now receive on https://accounts.intuit.com/index.html:

image

### CODE REVIEW

**Comment by apiology** [comment]
image

Another CSS fix in https://github.com/mintapi/mintapi/pull/552/commits/9af80cc15895b50b12b8c6b5527bcd32cf3bf74b for this page, which reproduced for me in headless mode.

**Comment by apiology** [comment]
https://github.com/mintapi/mintapi/pull/552/commits/d7d57d7a579c8dde7993077ca6af7027aab6e67f overcomes this page, which seems to offer the user the choice of password or a different factor: image

**Comment by apiology** [comment]
Verified that the patched mintapi works all the way through again in the custom Docker image I typically run mintapi in, though I'm experiencing #546 and #553 when running locally on macOS.

**Comment by apiology** [comment]
If folks want to try out my branch, this will do it: `pip uninstall mintapi && pip install git+https://github.com/apiology/mintapi.git@account_selection_css_alternative`

**Review by mrooney — APPROVED** [review]
Thanks for your help, looks good to me!

**Pull request merged**
